modLoader="javafml" #mandatory
loaderVersion="[27,)" #mandatory

[[mods]] #mandatory
	modId="globalxp" #mandatory
	version="v1.4.4" #mandatory
	displayName="Global XP" #mandatory
	description='''Adds a fast way to store XP and share it with your friends!''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/GlobalXP/issues"
	displayURL="http://minecraft.curseforge.com/projects/global-xp"
	authors="bl4ckscor3"

[[dependencies.globalxp]]
    modId="forge"
    mandatory=true
    versionRange="[27,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.globalxp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"